# Generated by Django 3.0.8 on 2020-08-29 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruktori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=50)),
                ('Emri_Prindit', models.CharField(default='', max_length=50)),
                ('Mbiemri', models.CharField(max_length=50)),
                ('nrLicenses', models.CharField(max_length=50, null=True)),
                ('dataLindjes', models.DateField(null=True)),
                ('NrPersonal', models.IntegerField(null=True)),
                ('komuna', models.CharField(max_length=50, null=True)),
                ('Nr_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='kandidatet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandatet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='muaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muaji', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Veturat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KategoriaMjetit', models.CharField(max_length=10)),
                ('Modeli', models.CharField(max_length=50)),
                ('NriAtestit', models.CharField(max_length=50)),
                ('NrVRC', models.IntegerField()),
                ('targat', models.CharField(max_length=50)),
                ('dataRegjistrimit', models.DateField()),
                ('dataKalimitTeRegjistrimit', models.DateField()),
                ('fotoja', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pagesatEinstruktorve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga', models.FloatField()),
                ('viti', models.IntegerField(default=2020)),
                ('Instruktori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Instruktori')),
                ('muaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.muaji')),
            ],
        ),
        migrations.CreateModel(
            name='pagesat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontabilisti', models.FloatField()),
                ('poligoni', models.FloatField()),
                ('qeraja', models.FloatField()),
                ('rryma', models.FloatField()),
                ('ligjerusi', models.FloatField()),
                ('Kontributet', models.FloatField()),
                ('viti', models.IntegerField(default=2020)),
                ('muaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.muaji')),
            ],
        ),
        migrations.CreateModel(
            name='Klientat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('Emri', models.CharField(max_length=50)),
                ('Emri_Prindit', models.CharField(default='', max_length=50)),
                ('Mbiemri', models.CharField(max_length=50)),
                ('NrPersonal', models.IntegerField()),
                ('DataLindjes', models.DateField(default=datetime.datetime.now)),
                ('Qmimi_Regjistrimit', models.IntegerField(default=0)),
                ('numriOreve', models.IntegerField(default=20)),
                ('borgj', models.FloatField(default=0)),
                ('Vendbanimi', models.CharField(max_length=100)),
                ('NrTelefonit', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Kursi', models.IntegerField(default=0)),
                ('data_Regjistrimit', models.DateField(default=datetime.datetime.now)),
                ('TerheqjaDokumenteve', models.BooleanField(default=False)),
                ('Vijimi', models.BooleanField(default=True)),
                ('dataTerheqjes', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('pagesaNeBank', models.CharField(default='Jo', max_length=2)),
                ('Instruktori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Instruktori')),
                ('kandi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.kandidatet')),
                ('tatimi', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.tat')),
            ],
        ),
        migrations.AddField(
            model_name='instruktori',
            name='vetura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Veturat'),
        ),
    ]
