# Generated by Django 3.0.8 on 2020-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klientat',
            old_name='kandi',
            new_name='kandatet',
        ),
    ]
