# Generated by Django 3.0.8 on 2020-08-29 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0002_auto_20200829_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
