# Generated by Django 3.0.8 on 2020-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0003_auto_20200829_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
