# Generated by Django 3.0.8 on 2020-08-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0004_auto_20200829_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidatet',
            name='kandatet',
            field=models.IntegerField(default=2020),
        ),
    ]
