# Generated by Django 3.1 on 2020-09-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0006_auto_20200829_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktori',
            name='vetura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.veturat'),
        ),
    ]
