# Generated by Django 3.2.7 on 2021-11-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0008_pagesat_administrata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voizitja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr', models.IntegerField()),
                ('Emri', models.CharField(max_length=500)),
                ('Data', models.DateField()),
                ('Ora', models.TimeField()),
                ('Pagesa', models.IntegerField()),
                ('Statusi', models.CharField(max_length=100)),
                ('PjesetNeHyrje', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='kandidatet',
            name='kandatet',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='pagesat',
            name='viti',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='pagesateinstruktorve',
            name='viti',
            field=models.IntegerField(default=2021),
        ),
    ]
