# Generated by Django 3.0.8 on 2020-08-20 12:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klientat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=50)),
                ('Mbiemri', models.CharField(max_length=50)),
                ('NrPersonal', models.IntegerField()),
                ('Addresa', models.CharField(max_length=100)),
                ('NrTelefonit', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
