# Generated by Django 3.0.8 on 2020-08-20 12:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='NrTelefonit',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
