# Generated by Django 3.0.8 on 2020-08-20 20:42

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0002_auto_20200820_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruktori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=50)),
                ('Mbiemri', models.CharField(max_length=50)),
                ('Nr_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.RenameField(
            model_name='klientat',
            old_name='Addresa',
            new_name='Vendbanimi',
        ),
        migrations.AddField(
            model_name='klientat',
            name='DataLindjes',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='klientat',
            name='Emri_Prindit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='klientat',
            name='Kursi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='klientat',
            name='Qmimi_Regjistrimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='klientat',
            name='TerheqjaDokumenteve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='klientat',
            name='data_Regjistrimit',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
