# Generated by Django 3.0.8 on 2020-08-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0003_auto_20200820_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='Instruktori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Instruktori'),
        ),
    ]
