# Generated by Django 3.0.8 on 2020-08-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0004_klientat_instruktori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='Instruktori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Instruktori'),
        ),
    ]
