# Generated by Django 3.0.8 on 2020-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0006_klientat_nrrendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='nrRendor',
            field=models.IntegerField(default=0),
        ),
    ]
