# Generated by Django 3.0.8 on 2020-08-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0008_auto_20200821_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klientat',
            name='nrRendor',
        ),
    ]
