# Generated by Django 3.0.8 on 2020-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0009_remove_klientat_nrrendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='nrRendor',
            field=models.IntegerField(default=1),
        ),
    ]
