# Generated by Django 3.0.8 on 2020-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0010_klientat_nrrendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='borgj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='klientat',
            name='numriOreve',
            field=models.IntegerField(default=20),
        ),
    ]
