# Generated by Django 3.0.8 on 2020-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0011_auto_20200821_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='Vijimi',
            field=models.BooleanField(default=True),
        ),
    ]
