# Generated by Django 3.0.8 on 2020-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0013_remove_klientat_nrrendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateField(null=True),
        ),
    ]
