# Generated by Django 3.0.8 on 2020-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0014_klientat_dataterheqjes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateTimeField(null=True),
        ),
    ]
