# Generated by Django 3.0.8 on 2020-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0015_auto_20200824_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='tat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat', models.CharField(max_length=5)),
            ],
        ),
    ]
