# Generated by Django 3.0.8 on 2020-08-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0017_klientat_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='tat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.tat'),
        ),
    ]
