# Generated by Django 3.0.8 on 2020-08-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0018_auto_20200824_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klientat',
            name='tat',
        ),
        migrations.AddField(
            model_name='klientat',
            name='tatimi',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Kosumi.tat'),
        ),
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
