# Generated by Django 3.0.8 on 2020-08-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0019_auto_20200824_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='muaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muaji', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vetyrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KategoriaMjetit', models.CharField(max_length=10)),
                ('Modeli', models.CharField(max_length=50)),
                ('NriAtestit', models.CharField(max_length=50)),
                ('NrVRC', models.IntegerField()),
                ('targat', models.CharField(max_length=50)),
                ('dataRegjistrimit', models.DateField()),
                ('dataKalimitTeRegjistrimit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pagesatEinstruktorve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga', models.FloatField()),
                ('Instruktori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.Instruktori')),
                ('muaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.muaji')),
            ],
        ),
        migrations.CreateModel(
            name='pagesat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontabilisti', models.FloatField()),
                ('poligoni', models.FloatField()),
                ('qeraja', models.FloatField()),
                ('rryma', models.FloatField()),
                ('ligjerusi', models.FloatField()),
                ('Kontributet', models.FloatField()),
                ('viti', models.IntegerField(default=2020)),
                ('muaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kosumi.muaji')),
            ],
        ),
    ]
