# Generated by Django 3.0.8 on 2020-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0020_muaji_pagesat_pagesateinstruktorve_vetyrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruktori',
            name='Emri_Prindit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instruktori',
            name='NrPersonal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instruktori',
            name='dataLindjes',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instruktori',
            name='komuna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instruktori',
            name='nrLicenses',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
