# Generated by Django 3.0.8 on 2020-08-26 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0025_auto_20200826_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
