# Generated by Django 3.0.8 on 2020-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0026_auto_20200826_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesateinstruktorve',
            name='viti',
            field=models.IntegerField(default=2020),
        ),
    ]
