# Generated by Django 3.0.8 on 2020-08-27 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0027_pagesateinstruktorve_viti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='dataTerheqjes',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
