# Generated by Django 3.0.8 on 2020-08-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0028_auto_20200827_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientat',
            name='pagesaNeBank',
            field=models.CharField(default='Jo', max_length=2),
        ),
        migrations.AlterField(
            model_name='veturat',
            name='fotoja',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
