# Generated by Django 3.0.8 on 2020-08-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0030_auto_20200827_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='kandidatet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandidatet', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='klientat',
            name='kandidatet',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Kosumi.kandidatet'),
        ),
    ]
