# Generated by Django 3.0.8 on 2020-08-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0031_auto_20200829_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientat',
            name='kandidatet',
            field=models.ForeignKey(default=0,on_delete=django.db.models.deletion.CASCADE, to='Kosumi.kandidatet'),
        ),
    ]
