# Generated by Django 3.0.8 on 2020-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0032_auto_20200829_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klientat',
            name='kandidatet',
        ),
    ]
