# Generated by Django 3.0.8 on 2020-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0034_klientat_nrrendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidatet',
            name='kandidatet',
            field=models.CharField(default='', max_length=50),
        ),
    ]
