# Generated by Django 3.0.8 on 2020-08-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kosumi', '0035_auto_20200829_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kandidatet',
        ),
    ]
